### ISSUE TITLE
Cheer for U

### ISSUE THREAD

**Issue by LovelyBuggies** [huangyz0918/personal-page-blog#1]
@huangyz0918 Hello, first I would like to thank you for your proposal template (I wrote you an email and you offered it to me generously). I am a GSoCer now and thank you so much!

Second, I saw your blog about the reasons for the gap year. Although we are not in the same research area, I am sure you are creating some amazing things (like https://github.com/huangyz0918/Hackintosh-Installer-University). I hope you have a great PhD journal! Best wishes!

**Comment by huangyz0918** [comment]
Congratulations @LovelyBuggies ! If you don't mind, we can connect via [WeChat](https://i.loli.net/2019/11/17/CRxUtkVZ8GLsnaO.jpg). Thanks!
